# Generated by Django 5.2.7 on 2025-11-25 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_file', models.DateField(default=django.utils.timezone.now)),
                ('vas_score', models.IntegerField(help_text='Daily VAS score (0-10)')),
                ('doctor_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_of_file'],
            },
        ),
    ]
