# Generated by Django 5.2.7 on 2025-12-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfile',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='vas_score',
            field=models.IntegerField(default=0, help_text='Daily VAS score (0-10)'),
        ),
    ]
