# Generated by Django 5.2.7 on 2025-11-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_file', '0001_initial'),
        ('medical_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfile',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='medical_record.medicalrecord'),
        ),
        migrations.AddIndex(
            model_name='medicalfile',
            index=models.Index(fields=['medical_record', '-date_of_file'], name='medical_fil_medical_cc20c6_idx'),
        ),
    ]
