# Generated by Django 5.2.7 on 2025-10-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='nezam_pezeshki_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='student_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
