# Generated by Django 5.2.7 on 2025-11-27 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0001_initial'),
        ('operators', '0002_operator_nezam_pezeshki_code_operator_student_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='case_name',
            new_name='document_id',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='operators.operator'),
        ),
    ]
