# Generated by Django 5.2.7 on 2025-11-30 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0002_operator_nezam_pezeshki_code_operator_student_code'),
        ('patients', '0005_rename_vas_average_patient_vas_5day_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_at', models.DateTimeField(auto_now_add=True)),
                ('task_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'OnGoing'), ('compelete', 'Completed'), ('ignored', 'Ignored')], default='ongoing', max_length=10)),
                ('operator_note', models.CharField(blank=True, max_length=500, null=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='operators.operator')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='patients.patient')),
            ],
        ),
    ]
