# Generated by Django 5.2.7 on 2025-12-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('ongoing', 'OnGoing'), ('ignored', 'Ignored'), ('compelete', 'Completed')], default='ongoing', max_length=10),
        ),
    ]
