# Generated by Django 5.2.7 on 2025-12-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('ignored', 'Ignored'), ('ongoing', 'OnGoing'), ('compelete', 'Completed')], default='ongoing', max_length=10),
        ),
    ]
