# medical_record/routing.py (Using a DRF Router)

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import MedicalRecordViewSet

# 1. Create a Router instance
router = DefaultRouter()

# 2. Register the ViewSet. 
# The base URL will be 'medical-files/', and 'medical-file' is the base name for reverse lookups.
router.register(r'medical-records', MedicalRecordViewSet, basename='medical-record')

urlpatterns = [
    # Include all URLs generated by the router
    path('', include(router.urls)),
]

# The router automatically generates these paths:
# -----------------------------------------------------------------------------------------------------
# URL Path                                    Method   ViewSet Method        Purpose
# -----------------------------------------------------------------------------------------------------
# /medical-records/                             POST     create                Create (your 'create' method)
# /medical-records/<pk>/                        PUT/PATCH update               Update (your 'update' method)
# /medical-records/<pk>/                        DELETE   destroy               Delete (your 'destroy' method)
# /medical-records/patient/<national_code>/     GET      get_by_patient        Custom action
# /medical-records/operator/<national_code>/    GET      get_by_operator       Custom action
# -----------------------------------------------------------------------------------------------------