# Generated by Django 5.2.7 on 2025-11-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('medical_file', '0001_initial'),
        ('patients', '0003_patient_current_operator_patient_vas_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='medical_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='medical_file.medicalfile'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='patients.patient'),
        ),
    ]
