# Generated by Django 5.2.7 on 2025-11-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_created_at_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_operator',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='vas_average',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatically calculated average of the last 5 VAS scores.', max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
