# Generated by Django 5.2.7 on 2025-11-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='vas_average',
            new_name='vas_5day_average',
        ),
    ]
