# Generated by Django 5.2.6 on 2025-09-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor')], default='DOCTOR', max_length=20),
        ),
    ]
